Add files via upload
A few interesting changes here:

* Users who don't have /etc/localtime or /etc/timezone can specify a file or symlink to use instead (see INSTALL for details).
* Validation for the same.
* More rigorous validation of the system-provided time zone for --local checks.
* Reorganized code and got rid of some unneeded "unset" calls to make the script less horrible in general.
* Perform checks for zoneinfo, local time zone, etc. only once to save time.
* "Query mode" was a holdover from pre-release wclock and served no useful purpose; removed.

diff --git a/wclock b/wclock
--- a/wclock
+++ b/wclock
@@ -25,54 +25,99 @@
 # A world clock script for terminal emulator and tty use.
 #
 
-unset QUERY
-unset city
-unset zone
-unset SUFFIX
-unset SLASHES
-unset THERE
-unset HERE
-unset NOECHO
-unset WRITTEN
-unset TCPARAMS
-unset PARAMSFIXED
-unset WARNED
-unset ZONEINFO
-unset DONE
-unset EXTRAS
-unset COMPAT
-unset ZONEPRELIM
-
 # "make install" sets these values at installation time.
 VER=
 SHAREDIR=
 ZONEPRELIM=
 ZONEINFO="$ZONEPRELIM"
+TIMESETTER=
 
-# This method selects an appropriate zoneinfo directory, if none was provided
-# when running "make install."
+# This method selects a zoneinfo directory. If an appropriate zoneinfo directory
+# was passed to "make install," it will not run.
 
 getzoneinfo (){
-if [ -d "/usr/share/zoneinfo-leaps" ]; then
-	ZONEINFO=/usr/share/zoneinfo-leaps
-elif [ -d "/usr/share/zoneinfo" ]; then
-	ZONEINFO=/usr/share/zoneinfo
-elif [ -d "/usr/local/share/zoneinfo-leaps" ]; then
-	ZONEINFO=/usr/local/share/zoneinfo-leaps
-elif [ -d "/usr/local/share/zoneinfo" ]; then
-	ZONEINFO=/usr/local/share/zoneinfo
-elif [ -d "/etc/zoneinfo-leaps" ]; then
-	ZONEINFO=/etc/zoneinfo-leaps
-elif [ -d "/etc/zoneinfo" ]; then
-	ZONEINFO=/etc/zoneinfo
-# To get compatibility for another zoneinfo location, please don't hesitate to
-# raise a GitHub issue!
+for x in /usr/share/zoneinfo-leaps \
+	 /usr/share/zoneinfo \
+	 /usr/local/share/zoneinfo-leaps \
+	 /usr/local/share/zoneinfo \
+	 /etc/zoneinfo-leaps \
+	 /etc/zoneinfo; do
+	if [ -d "$x" ]; then
+		$SHAREDIR/wclock/validate-zoneinfo "$x"
+		[ -z "$CHECKZONEINFO" ] && ZONEINFO="$x" && return
+	fi
+done
+echo
+echo '	'A valid zoneinfo directory was not found. Exiting.
+echo
+exit
+}
+
+# This method checks the provided zoneinfo directory (if any) and calls
+# getzoneinfo if necessary.
+
+checkzoneinfo (){
+# Acquiring zoneinfo if necessary, exiting if none can be found.
+if [ -z "$ZONEINFO" ] || [ ! -d "$ZONEINFO" ]; then
+	getzoneinfo
 else
-	echo
-	echo '	'The zoneinfo directory was not found. Exiting.
-	echo
-	exit
+	# Making sure that zoneinfo is well-formed.
+	"$SHAREDIR"/wclock/validate-zoneinfo "$ZONEINFO"
+	[ "$CHECKZONEINFO" = "yes" ] && getzoneinfo
 fi
+
+# Although at least one of these should be available in Linux installations,
+# just to be safe.
+if [ -d "$ZONEINFO/right" ]; then
+	SUFFIX="right/"
+elif [ -d "$ZONEINFO/posix" ]; then
+	SUFFIX="posix/"
+fi
+
+SLASHES="$(echo "$ZONEINFO/$SUFFIX" | tr -cd '/' | wc -c)"
+SLASHES=$((SLASHES + 1))
+}
+
+# Use this method to check on potential files that set the time zone.
+
+tzfilecheck (){
+# Simplest case: the file is a time zone file (or a symlink to a time zone
+# file).
+unset PWD
+PWD="$(pwd)"
+cd "$(dirname "$1")"
+CHECKER="$(file "$(readlink "$1")" | cut -d':' -f2- | grep timezone)"
+[ -n "$CHECKER" ] && HEREZONE="$(readlink "$1")"
+cd "$PWD"
+# The file is a text document with a time zone.
+if [ ! -h "$1" ] && [ -z "$HEREZONE" ]; then
+	HEREZONE="$(cat "$1")"
+	CHECKER2="$(find "$ZONEINFO" -type f,l | grep -i -m 1 "$HEREZONE")"
+	[ -z "$CHECKER2" ] && unset HEREZONE
+fi
+[ -n "$HEREZONE" ] && WORKING=yes
+}
+
+# This method displays the results (empty echoes and other messaging handled in
+# main, comparemethod, etc.).
+
+timedisplay (){
+case "$1" in
+        NOFIGURE)
+        [ -z "$WRITTEN2" ] && echo '	'"$(date "$ENTRY" +"%X %Z %x (%a)")"'	'Here
+        echo '	'"$(TZ="$place" date "$ENTRY" +"%X %Z %x (%a)")"'	'"$headup"
+        ;;
+        *)
+        if [ "$X" != "1 $ZONETEMP" ] && [ "$1" != "ALWAYSPLACE" ]; then
+                headup="$place"
+                [ -z "$WRITTEN" ] && echo '	'"$name" && echo && WRITTEN=yes
+        else
+                headup="$name ($place)"
+        fi
+        [ -z "$TCPARAMS" ] && echo '	'"$(TZ="$place" date +"%X %Z %x (%a)")"'	'"$headup"
+        [ -n "$TCPARAMS" ] && comparemethod
+        ;;
+esac
 }
 
 # If a local time zone cannot be found when calling --local, this method will
@@ -93,7 +138,7 @@ if [ "$HERE" = "yes" ]; then
 		# that point form a valid "date" string when followed by the
 		# local time offset, then the last argument tested is the
 		# time of day.
-		while [ ! "$count" -gt "$SPACES" ] && [ "$OK" != "yes" ]; do
+		while [ ! "$count" -gt "$SPACES" ] && [ -z "$OK" ]; do
 			cutpoint="$((count +1))"
 			tester="$(echo "$TCPARAMS" | cut -d' ' -f"$cutpoint")"
 			tester2="$tester$(date +%z)"
@@ -101,7 +146,7 @@ if [ "$HERE" = "yes" ]; then
 			date --date="$tester2" > /dev/null 2>&1 && OK=yes || true
 			# Mitigating three- and four-digit times without colons
 			# not working with time offsets in "date".
-			if [ "$OK" != "yes" ]; then
+			if [ -z "$OK" ]; then
 				# Isolating the argument that's being examined.
 				[ "$cutpoint" = "1" ] && isolate="$tester"
 				[ "$cutpoint" != "1" ] && isolate="$(echo "$tester" | cut -d' ' -f-"$((cutpoint - 1))" | cut -d' ' -f"$cutpoint"-)"
@@ -166,8 +211,7 @@ if [ "$THERE" = "yes" ]; then
 	ENTRY="--date=TZ=\""$place"\" $TCPARAMS"
 	# Error-checking
 	TZ="$place" date "$ENTRY" > /dev/null 2>&1 || { echo '	'The check date for "$headup" appears to have a formatting error. ; return ; }
-	echo '	'$(date "$ENTRY" +"%X %Z %x (%a)")'	'Here
-	echo '	'"$(TZ="$place" date "$ENTRY" +"%X %Z %x (%a)")"'	'"$headup"
+	timedisplay NOFIGURE
 	# Want echoes between different time zones, but not at the end of the
 	# script or before the next break flag.
 	echo && NOECHO=yes
@@ -175,16 +219,17 @@ fi
 
 # --local flag was used.
 if [ "$HERE" = "yes" ]; then
-	if [ -h "/etc/localtime" ]; then
-		SLASHES2="$(echo "$ZONEINFO/" | tr -cd '/' | wc -c)"
-		SLASHES2=$((SLASHES2 + 1))
-		HEREZONE="$(readlink /etc/localtime | cut -d'/' -f"$SLASHES2"-)"
-	elif [ -f "/etc/timezone" ]; then
-		# Debian compatibility.
-		HEREZONE="$(cat /etc/timezone)"
-	else
+	unset WORKING
+	# If TIMESETTER was passed at install time, test that first.
+	[ -n "$TIMESETTER" ] && [ -f "$TIMESETTER" ] && [ -z "$HEREZONE" ] && tzfilecheck "$TIMESETTER"
+	# Standard configuration.
+	[ -f "/etc/localtime" ] && [ -z "$HEREZONE" ] && [ -z "$WORKING" ] && tzfilecheck /etc/localtime
+	# Debian compatibility.
+	[ -f "/etc/timezone" ] && [ -z "$HEREZONE" ] && [ -z "$WORKING" ] && tzfilecheck /etc/timezone
+	if [ -z "$HEREZONE" ]; then
 		# In case the time zone setting method references neither
-		# /etc/localtime nor /etc/timezone.
+		# /etc/localtime nor /etc/timezone, and no valid TIMESETTER
+		# was passed at installation time.
 		SHORTDATE="$(date --date="$TCPARAMS" +"%-z")"
 		TRYDATE=GMT"${SHORTDATE%00}"
 		if [ -f "$ZONEINFO/"$SUFFIX"Etc/$TRYDATE" ]; then
@@ -212,7 +257,7 @@ if [ "$HERE" = "yes" ]; then
 				;;
 				+630)
 				# Most-populated
-				if [ -f "$ZONEINFO/$SUFFIX"Asia/Yangon ] || [ -h "$ZONEINFO/$SUFFIX"Asia/Yangon ]; then
+				if [ -f "$ZONEINFO/$SUFFIX"Asia/Yangon ]; then
 					HEREZONE=Asia/Yangon
 				else
 					# For backwards compatibility.
@@ -239,45 +284,54 @@ if [ "$HERE" = "yes" ]; then
 	if [ -n "$HEREZONE" ]; then
 		# Etc/* time zones have inverted signs; fix this here if
 		# needed.
-		unset FIRSTCHARS
-		FIRSTCHARS="$(echo "$HEREZONE" | cut -c7 | cut -c2-)"
-		case "$FIRSTCHARS" in
-			/+)
-			HEREZONE="$(echo "$HEREZONE" | tr '+' '-')"
-			;;
-			/-)
-			HEREZONE="$(echo "$HEREZONE" | tr '-' '+')"
-			;;
-		esac
+		if [ -z "$HEREZONEOK" ] && [ -n "$(echo "$HEREZONE" | grep "Etc/")" ]; then
+			HEREZONE="$(echo "$HEREZONE" | tr 'Etc/+' 'Etc/X')"
+			HEREZONE="$(echo "$HEREZONE" | tr 'Etc/-' 'Etc/Y')"
+			HEREZONE="$(echo "$HEREZONE" | tr 'Etc/X' 'Etc/-')"
+			HEREZONE="$(echo "$HEREZONE" | tr 'Etc/Y' 'Etc/+')"
+			HEREZONEOK=yes
+		fi
 		ENTRY="--date=TZ=\""$HEREZONE"\" $TCPARAMS"
 		# Error-checking
-		TZ="$place" date "$ENTRY" > /dev/null 2>&1 || { echo '	'The check date for "$headup" appears to have a formatting error. ; return ; }
-		# The local time should only be written out once if there are
-		# multiple time zones for comparison.
-		[ "$WRITTEN" != "yes" ] && echo '	'"$(date "$ENTRY" +"%X %Z %x (%a)")"'	'Here
-		echo '	'$(TZ="$place" date "$ENTRY" +"%X %Z %x (%a)")'	'"$headup"
-		WRITTEN=yes
-	else
+		if [ -z "$WRITTEN2" ]; then
+			TZ="$place" date "$ENTRY" > /dev/null 2>&1 || { echo '	'The check date for "$headup" appears to have a formatting error. ; return ; }
+		fi
+		timedisplay NOFIGURE
+		WRITTEN2=yes
+	elif [ -z "$HEREZONE" ] || [ "$WASMISSING" = "yes" ]; then
 		# An alternative method to be used if the actual local time 
 		# zone can't be found. Somewhat unreliable, as seen in the
 		# echo statements below.
-		fallback
+
+		# If this actually happens to you, please raise a GitHub issue
+		# or email the author; it's that weird. See man 1 wclock for
+		# contact information.
+		[ -z "$HEREZONE" ] && fallback && WASMISSING=yes
+		if [ -z "$WRITTEN3" ]; then
+			echo '	'No local time zone could be found. If the times shown
+			echo '	'above fall on different days, the earlier time will
+			echo '	'be exactly 24 hours earlier than it should be.
+			echo
+			WRITTEN3=yes
+		fi
 		ENTRY="--date=TZ=\""$place"\" $TCPARAMS"
-		TZ="$place" date "$ENTRY" > /dev/null 2>&1 || { echo '	'The check date for "$headup" appears to have a formatting error. ; return ; }
-		[ "$WRITTEN" != "yes" ] && echo '	'"$(date "$ENTRY" +"%X %Z %x (%a)")"'	'Here
-		echo '	'$(TZ="$place" date "$ENTRY" +"%X %Z %x (%a)")'	'"$headup"
-		WRITTEN=yes
-		echo
-		echo '	'No local time zone could be found. If the times shown
-		echo '	'above fall on different days, the earlier time will
-		echo '	'be exactly 24 hours earlier than it should be.
+		if [ -z "$WRITTEN2" ]; then
+			TZ="$place" date "$ENTRY" > /dev/null 2>&1 || { echo '	'The check date for "$headup" appears to have a formatting error. ; return ; }
+		fi
+		timedisplay NOFIGURE
+		WRITTEN2=yes
 	fi
+	[ -z "$WRITTEN2" ] && echo && NOECHO=yes
 fi
 }
 
 # The main loop for each country/city search argument.
 
 main (){
+# This only happens if the last search argument is missing; other defective
+# arguments are cleared during the case loop.
+[ -z "$city" ] && echo && echo '	'No search arguments. && return
+
 # For users without a HOME directory, use /tmp instead.
 if [ -n "$HOME" ] && [ -d "$HOME" ]; then
 	ZONETEMP="$HOME/.zonetemp"
@@ -298,28 +352,10 @@ fi
 EXTRAS="$SHAREDIR"/wclock/extras
 COMPAT="$SHAREDIR"/wclock/compat
 
-# Acquiring zoneinfo if necessary, exiting if none can be found.
-[ -z "$ZONEINFO" ] || [ ! -d "$ZONEINFO" ] && getzoneinfo
+[ -z "$NOECHO" ] && echo
 
-# Although at least one of these should be available in Linux installations,
-# just to be safe.
-if [ -d "$ZONEINFO/right" ]; then
-	SUFFIX="right/"
-elif [ -d "$ZONEINFO/posix" ]; then
-	SUFFIX="posix/"
-fi
-
-SLASHES="$(echo "$ZONEINFO/$SUFFIX" | tr -cd '/' | wc -c)"
-SLASHES=$((SLASHES + 1))
-
-[ "$QUERY" != "yes" ] && [ -z "$city" ] && echo && echo '	'No search arguments. && wclock --help && exit
-# A blank query mode call displays available directories.
-[ "$QUERY" = "yes" ] && [ -z "$city" ] && find "$ZONEINFO"/"$SUFFIX" -type d | cut -d'/' -f"$SLASHES"- | less && exit
-
-[ "$NOECHO" != "yes" ] && echo
-
-# If the extras file is missing, just check the directories directly.
-[ "$WARNED" != "yes" ] && [ ! -f "$EXTRAS" ] && echo '	'"$EXTRAS" was not found. Only named time zones in && echo '	'"$ZONEINFO"/"$SUFFIX" will be searched. && WARNED=yes && echo
+# If the extras file is missing, only the directories will be checked.
+[ -z "$WARNED" ] && [ ! -f "$EXTRAS" ] && echo '	'"$EXTRAS" was not found. Only named time zones in && echo '	'"$ZONEINFO"/"$SUFFIX" will be searched. && WARNED=yes && echo
 
 unset TIMESTAMP
 
@@ -335,53 +371,33 @@ unset DONE
 [ -f "$EXTRAS" ] && zone="$(grep -i "^$city	" "$EXTRAS")"
 [ -n "$zone" ] && echo "$zone" > "$ZONETEMP"
 unset WRITTEN
+unset WRITTEN2
+unset WRITTEN3
 [ -f "$ZONETEMP" ] && while read -r line; do
 	X="$(wc -l "$ZONETEMP")"
 	unset name
 	unset place
 	# "name" is the name of the city; "place" is the time zone.
-	name="$(echo "$line" | cut -d'	' -f1)"
+	name="$(echo "$line" | cut -d'	' -f1 | tr '_' ' ')"
 	place="$(echo "$line" | cut -d'	' -f2-)"
-
-	# For display purposes (in practical terms, headup should never be
-	# "place" here except for countries with multiple time zones).
-	if [ ! "$X" = "1 $ZONETEMP" ]; then
-		headup="$place"
-		[ "$WRITTEN" != "yes" ] && echo '	'"$name" | tr '_' ' ' && echo && WRITTEN=yes
-	else
-		headup="$(echo "$name" | tr '_' ' ') ($place)"
-	fi
 
 	# For backwards compatibility, only use the time zone from the extras
 	# file if that time zone actually exists on the system. If it does not,
 	# proceed to the COMPAT loop.
-	if [ -f "$ZONEINFO/$SUFFIX""$place" ] || [ -h "$ZONEINFO/$SUFFIX""$place" ]; then
-		# No time check.
-		[ -z "$TCPARAMS" ] && echo '	'"$(TZ="$place" date +"%X %Z %x (%a)")"'	'"$headup"
-		# Time check.
-		[ -n "$TCPARAMS" ] && comparemethod
+	if [ -f "$ZONEINFO/$SUFFIX""$place" ]; then
+		timedisplay
 		DONE=yes
 	# For old versions of tzdata (back to 2012a)
 	elif [ -f "$COMPAT" ] && [ -n "$(grep -m 1 "$place" "$COMPAT")" ]; then
 		place="$(grep -m 1 "$place" "$COMPAT" | cut -d'	' -f2-)"
-		# Easier to just do this again here if necessary. Rare case.
-		if [ ! "$X" = "1 $ZONETEMP" ]; then
-			headup="$place"
-			[ "$WRITTEN" != "yes" ] && echo '	'"$name" | tr '_' ' ' && echo && WRITTEN=yes
-		else
-			headup="$(echo "$name" | tr '_' ' ') ($place)"
-		fi
-		# No time check.
-		[ -z "$TCPARAMS" ] && echo '	'"$(TZ="$place" date +"%X %Z %x (%a)")"'	'"$headup"
-		# Time check.
-		[ -n "$TCPARAMS" ] && comparemethod
+		timedisplay
 		DONE=yes
 	fi
 done < "$ZONETEMP"
 
 unset DONE2
 
-if [ "$DONE" != "yes" ]; then
+if [ -z "$DONE" ]; then
 	# Otherwise, search for a match among the named time zones.
 	unset zone
 	zone="$(find "$ZONEINFO"/"$SUFFIX"* -type f,l | grep -i "$city" | cut -d'/' -f"$SLASHES"-)"
@@ -399,7 +415,7 @@ if [ "$DONE" != "yes" ]; then
 			[ -n "$Y" ] && EXACTMATCH="yes"
 		done < "$ZONETEMP"
 	fi
-	if [ "$EXACTMATCH" != "yes" ] || [ ! -f "$ZONETEMP" ]; then
+	if [ -z "$EXACTMATCH" ] || [ ! -f "$ZONETEMP" ]; then
 		[ -f "$EXTRAS" ] && zones="$(grep -i "$city\w*[[:space:]]" "$EXTRAS")"
 	fi
 
@@ -409,10 +425,7 @@ if [ "$DONE" != "yes" ]; then
 			# For display purposes.
 			name="$(basename "$place" | tr '_' ' ')"
 			X="$(wc -l "$ZONETEMP")"
-			headup="$name ($place)"
-		
-			[ -z "$TCPARAMS" ] && echo '	'"$(TZ="$place" date +"%X %Z %x (%a)")"'	'"$headup"
-			[ -n "$TCPARAMS" ] && comparemethod
+			timedisplay ALWAYSPLACE
 			DONE2=yes
 		done < "$ZONETEMP"
 	fi
@@ -425,20 +438,22 @@ if [ "$DONE" != "yes" ]; then
 			X="$(wc -l "$ZONETEMP")"
 			unset name
 			unset place
-			name="$(echo "$line" | cut -d'	' -f1)"
+			name="$(echo "$line" | cut -d'	' -f1 | tr '_' ' ')"
 			place="$(echo "$line" | cut -d'	' -f2-)"
-		
-			headup="$(echo "$name" | tr '_' ' ') ($place)"
-		
-			[ -z "$TCPARAMS" ] && echo '	'"$(TZ="$place" date +"%X %Z %x (%a)")"'	'"$headup"
-			[ -n "$TCPARAMS" ] && comparemethod
-			DONE2=yes
+			if [ -f "$ZONEINFO/$SUFFIX""$place" ]; then
+				timedisplay ALWAYSPLACE
+				DONE2=yes
+			elif [ -f "$COMPAT" ] && [ -n "$(grep -m 1 "$place" "$COMPAT")" ]; then
+				place="$(grep -m 1 "$place" "$COMPAT" | cut -d'	' -f2-)"
+				timedisplay ALWAYSPLACE
+				DONE2=yes
+			fi
 		done < "$ZONETEMP"
 	fi
 	
 	# A last-ditch attempt with COMPAT, in case of old version and unlucky
 	# time zone check.
-	if [ "$DONE2" != "yes" ] && [ -f "$COMPAT" ]; then
+	if [ -z "$DONE2" ] && [ -f "$COMPAT" ]; then
 		unset zone
 		zone="$(grep -i "/$city	" "$COMPAT")"
 		[ -n "$zone" ] && echo "$zone" > "$ZONETEMP"
@@ -447,26 +462,9 @@ if [ "$DONE" != "yes" ]; then
 			X="$(wc -l "$ZONETEMP")"
 			unset name
 			unset place
-			# "name" is the name of the city; "place" is the time 
-			# zone.
 			name="$(echo "$line" | cut -d'/' -f2- | cut -d'	' -f1 | tr '_' ' ')"
 			place="$(echo "$line" | cut -d'	' -f2-)"
-
-			# For display purposes (in practical terms, headup 
-			# should never be "place" here except for countries with
-			# multiple time zones).
-			if [ ! "$X" = "1 $ZONETEMP" ]; then
-				headup="$place"
-				[ "$WRITTEN" != "yes" ] && echo '	'"$name" | tr '_' ' ' && echo && WRITTEN=yes
-			else
-				headup="$(echo "$name" | tr '_' ' ') ($place)"
-			fi
-			if [ -f "$ZONEINFO/$SUFFIX""$place" ] || [ -h "$ZONEINFO/$SUFFIX""$place" ]; then
-				# No time check.
-				[ -z "$TCPARAMS" ] && echo '	'"$(TZ="$place" date +"%X %Z %x (%a)")"'	'"$headup"
-				# Time check.
-				[ -n "$TCPARAMS" ] && comparemethod
-			fi
+			[ -f "$ZONEINFO/$SUFFIX""$place" ] && timedisplay
 		done < "$ZONETEMP"
 	fi
 
@@ -481,6 +479,19 @@ if [ -f "$ZONETEMP-$TIMESTAMP" ] || [ -d "$ZONETEMP-$TIMESTAMP" ] || [ -h "$ZONE
 fi
 }
 
+unset city
+unset SUFFIX
+unset SLASHES
+unset THERE
+unset HERE
+unset NOECHO
+unset TCPARAMS
+unset PARAMSFIXED
+unset WARNED
+unset HEREZONE
+unset HEREZONEOK
+unset WASMISSING
+
 for arg in "$@"; do
 	case "$arg" in 
 		-h|--help)
@@ -491,14 +502,7 @@ for arg in "$@"; do
 		echo wclock [-t\|--there DATETIME -b] SEARCH [-b\|--break SEARCH] ...
 		echo wclock [-l\|--local DATETIME -b] SEARCH [-b\|--break SEARCH] ...
 		echo
-		echo QUERY MODE:
-		echo wclock -q\|--query [DIRECTORY]
-		echo
 		echo OPTIONS:
-		echo -q\|--query - With DIRECTORY, display defined time zones in the specified time zone directory.
-		echo '	'Without DIRECTORY, display all directories under "$ZONEINFO" with time zone data.
-		echo '	'Incompatible with -b, -t and -l.
-		echo
 		echo -b\|--break - Enter between search terms to retrieve multiple time zones.
 		echo
 		echo -t\|--there - Find your local time when it is DATETIME in SEARCH.
@@ -528,20 +532,19 @@ for arg in "$@"; do
 		;;
 		-v|--version)
 		echo
-		echo wclock-"$VER"
-		echo Written against tzdata-2021b \(compatible from tzdata-2012a onward\).
+		echo '	'wclock-"$VER"
+		echo '	'Written against tzdata-2021b \(compatible from tzdata-2012a onward\).
 		echo
 		exit
 		;;
-		-q|--query)
-		QUERY=yes		
-		;;
 		-b|--break)
+		[ -z "$CHECKEDZONEINFO" ] && checkzoneinfo && CHECKEDZONEINFO=yes
 		[ -n "$city" ] &&  main
 		unset city
 		unset GETPARAM
 		;;
 		-t|--there)
+		[ -z "$CHECKEDZONEINFO" ] && checkzoneinfo && CHECKEDZONEINFO=yes
 		[ -n "$city" ] && main
 		unset city
 		unset HERE	
@@ -551,6 +554,7 @@ for arg in "$@"; do
 		THERE=yes
 		;;
 		-l|--local)
+		[ -z "$CHECKEDZONEINFO" ] && checkzoneinfo && CHECKEDZONEINFO=yes
 		[ -n "$city" ] && main
 		unset city
 		unset THERE
@@ -560,13 +564,10 @@ for arg in "$@"; do
 		HERE=yes
 		;;
 		*)
-		# Query with another argument
-		if [ "$QUERY" = "yes" ]; then
-			find "$ZONEINFO"/"$SUFFIX" -type f,l | grep -i "$arg" | cut -d'/' -f6- | cut -d'/' -f2- | sort | less
-			exit
+		[ -z "$CHECKEDZONEINFO" ] && checkzoneinfo && CHECKEDZONEINFO=yes
 		# Gather arguments for specific time checks between -t or -l and
 		# any other parameter.
-		elif [ "$GETPARAM" = "yes" ]; then
+		if [ "$GETPARAM" = "yes" ]; then
 			if [ -z "$TCPARAMS" ]; then 
 				TCPARAMS="$arg"
 			else
@@ -581,4 +582,4 @@ for arg in "$@"; do
 	esac
 done
 main
-[ "$NOECHO" != "yes" ] && echo
+[ -z "$NOECHO" ] && echo
